### ISSUE TITLE
Add Highcharts.setOptions function. Also Global and Lang classes

### ISSUE THREAD

**Issue by eloypastor** [gonzalopezzi/highcharts_api_gen#3]
Add this to Dart-JS interoperability:

```
Highcharts.setOptions({
    global: {
        Date: undefined
        VMLRadialGradientURL: "http://code.highcharts.com/{version}/gfx/vml-radial-gradient.png"
        canvasToolsURL: "http://code.highcharts.com/{version}/modules/canvas-tools.js"
        getTimezoneOffset:
        timezoneOffset: 0
        useUTC: true
    }
    lang: {
        contextButtonTitle: "Chart context menu"
        decimalPoint: "."
        downloadJPEG: "Download JPEG image"
        downloadPDF: "Download PDF document"
        downloadPNG: "Download PNG image"
        downloadSVG: "Download SVG vector image"
        drillUpText: "Back to {series.name}"
        invalidDate:
        loading: "Loading..."
        months: [ "January" , "February" , "March" , "April" , "May" , "June" , "July" , "August" , "September" , "October" , "November" , "December"]
        noData: "No data to display"
        numericSymbols: [ "k" , "M" , "G" , "T" , "P" , "E"]
        printChart: "Print chart"
        resetZoom: "Reset zoom"
        resetZoomTitle: "Reset zoom level 1:1"
        shortMonths: [ "Jan" , "Feb" , "Mar" , "Apr" , "May" , "Jun" , "Jul" , "Aug" , "Sep" , "Oct" , "Nov" , "Dec"]
        shortWeekdays: undefined
        thousandsSep: " "
        weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
    }
}
```
